import type { Metadata, Viewport } from "next";

import { Montserrat } from 'next/font/google'
import localFont from "next/font/local"
import "./globals.css";

import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

// const brexon = localFont({
//   src: "../assets/fonts/brexon.regular.ttf",
//   variable: "--font-header"
// })

const montserrat = Montserrat({
  variable: "--font-body",
  subsets: ['latin']
})
const clashDisplay = localFont({
  src: "../assets/fonts/ClashDisplay-Variable.ttf",
  variable: "--font-header"

})

export const metadata: Metadata = {
  title: "Manila SBK Overdose",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  // height: "device-height", 
  // width: "device-width", 
  // initialScale: 1, 
  minimumScale: 1,
  // targetDensity: "device-dpi"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${clashDisplay.className} ${montserrat.className}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
